import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import { roboto } from "@/app/ui/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
      <body className={`${roboto.className} antialiased min-h-full flex flex-col `}>
        <Navbar/>
        <div className="container mx-auto px-4">
          {children}
        </div>
      </body>
    </html>
  );
}
